//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DixonsCarphone.Wfm.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOpeningTime
    {
        public Nullable<double> UNI_ID_OPEN { get; set; }
        public Nullable<double> CST_CNTR_ID { get; set; }
        public Nullable<double> CST_CNTR_SID { get; set; }
        public Nullable<double> WEEK_COMMENCE { get; set; }
        public Nullable<double> SUN_OPEN { get; set; }
        public Nullable<double> SUN_CLOSE { get; set; }
        public Nullable<double> MON_OPEN { get; set; }
        public Nullable<double> MON_CLOSE { get; set; }
        public Nullable<double> TUE_OPEN { get; set; }
        public Nullable<double> TUE_CLOSE { get; set; }
        public Nullable<double> WED_OPEN { get; set; }
        public Nullable<double> WED_CLOSE { get; set; }
        public Nullable<double> THU_OPEN { get; set; }
        public Nullable<double> THU_CLOSE { get; set; }
        public Nullable<double> FRI_OPEN { get; set; }
        public Nullable<double> FRI_CLOSE { get; set; }
        public Nullable<double> SAT_OPEN { get; set; }
        public Nullable<double> SAT_CLOSE { get; set; }
        public Nullable<System.DateTime> DATE_SUBMIT { get; set; }
        public Nullable<double> IS_CURRENT { get; set; }
        public Nullable<double> IS_PENDING { get; set; }
        public Nullable<double> USER_ID { get; set; }
        public string UNI_REPLACEMENT { get; set; }
        public Nullable<double> ADMIN_UPDATING { get; set; }
        public Nullable<double> REJECTED_UPDATE { get; set; }
        public int StoreOpenTimeId { get; set; }
    }
}
